### ISSUE TITLE
Module in package.json

### ISSUE THREAD

**Issue by pawojciechowski** [mhssmnn/redux-form-saga#22]
Hi there!

After upgrading to v0.1.1 - there are `const` declarations instead of `var` in a code transpiled by Webpack 2 + Babel to ES5 (It's not working on Safari 9.1.3 with "strict" mode set by default by Webpack bundler). It's because you've added "module" to the package.json file. It's probably not the desired behavior.

EDIT:
Probably connected with this:
https://github.com/webpack/webpack/issues/1979 
and maybe with this https://github.com/babel/babel-loader/issues/149

**Comment by jaridmargolin** [comment]
@pawojciechowski - I added the `module` entry in #21 due to:

> Was running into an issue where the redux-form-saga dist required "regeneratorRuntime" but my webpack build was not producing it based on the browser matrix I provided to babel-preset-env.

Apologies if this resulted in errors on your end. Perhaps it should have been published as a "breaking change"? Sometimes it is not immediately clear that a change will cause downstream errors.

---

Anyways, you should be able to resolve your issue by utilizing [babel-plugin-transform-es2015-block-scoping](https://www.npmjs.com/package/babel-plugin-transform-es2015-block-scoping)

**Comment by pawojciechowski** [comment]
Sadly, it doesn't work with that library too, cause code is not transpiled by Babel anyway. Now I'm using v0.1.0, and it works, so I haven't dive into that yet.

**Comment by jaridmargolin** [comment]
@mhssmnn - @pawojciechowski  is actually spot on here. While the webpack docs do show an [example](https://webpack.js.org/guides/author-libraries/#final-steps) pointing to src...

```
{
    "main": "dist/webpack-numbers.js",
    "module": "src/index.js", // To add as standard module as per https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md#typical-usage
}
```

there is actually a note right below that I overlooked.

> module will point to a module that has ES2015 module syntax but otherwise only syntax features that browser/node supports.

This means the library author must decide what browsers and node versions the ES2015 `module` will support.

The `src` code alone satisfied the browser targets and node targets I personally need, but it appears it did not satisfy the needs of @pawojciechowski.

@mhssmnn if you can draw a line on what exact browser versions you want to support, I can ensure the `module` property is inline that with that.

If it is decided to support browsers that do not have [native support for generators](https://kangax.github.io/compat-table/es6/#test-generators) (Safari < 10 and IE), I will be back at my original problem caused by redux-form-saga making reference to regenerator-runtime. If you are willing, I could additionally add an `esnext` build/property as outlined here: http://2ality.com/2017/06/pkg-esnext.html . This would allow consumers who support evergreen browsers, as I am, to utilize the package.

**Comment by BigBuckBunny** [comment]
I was having the same problem with the non transpiled code and after looking at the project files I had to change my imports to the following to get webpack to work. 

import formActionSaga from 'redux-form-saga/lib';

In your package.json your build statement puts the transpiled code into lib:
"build": "NODE_ENV=production ./node_modules/.bin/babel src/ --out-dir lib/".

Hope this helps

**Comment by afitiskin** [comment]
@pawojciechowski @BigBuckBunny @jaridmargolin I've just submitted PR to fix the issue. I splitted build process into 2 parts: CommonJS version and ES version. It should works normally for all envitoments. Please check it!

https://github.com/mhssmnn/redux-form-saga/pull/23

**Comment by jaridmargolin** [comment]
@afitiskin - at a first glance this looks right to me.

I'd love to see this as well: https://github.com/skatejs/skatejs/pull/1187, but perhaps it could/should be an additional PR?
